export { About } from './about'
export { Error } from './error'
export { Home } from './home'
export { Inventory } from './inventory'
export { Login } from './login'
export { Profile } from './profile'
export { SignUp } from './sign-up'
